# Generation parameters
generate: individuals
num_to_generate: 78
availability_likelihood: 0.78   # Chance of a member being available per option

# The following parameters are only used for generating groups
min_members_per_group: 6        # Number of members per groups
max_members_per_group: 7        # Number of members per groups

# Available slots information
num_boats: 3                    # Number of boats per timeslot  
num_timeslots: 3                # Number of timeslots per day
num_days: 3                     # Number of days available
courses_per_team: 2             # Number of courses to schedule per team/individual

# The following parameters are only used in group scheduling mode
min_available: 5                # Number of members that must be available in a session

# Evolutionary algorithm parameters
profile: progression 20
population: 400                 # Size of a generation (higher = more processing time, more global optimization)
