# The following parameters are only used for generating groups
generate: groups
num_to_generate: 40             # Number of groups to generate
min_members_per_group: 5        # Number of members per group
max_members_per_group: 8        # Number of members per group
availability_likelihood: 0.78   # Chance of a member being available per option

# Available slots information
num_boats: 5                    # Number of boats per timeslot  
num_timeslots: 4                # Number of timeslots per day
num_days: 5                     # Number of days available
courses_per_team: 2             # Number of courses to schedule per team/individual

# The following parameters are only used in group scheduling mode
min_available: 5                # Number of members that must be available in a session

# Evolutionary algorithm parameters
generations: 400                # Number of generations (higher = more processing time, more local optimization)
population: 400                 # Size of a generation (higher = more processing time, more global optimization)
indpb: 0.05                     # Mutation probability (higher = more global optimization, less local optimization)c